# -*- coding: utf-8 -*-
"""FinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15wgKTfL92uCGlLVo_GRJ_0CBy2d6VhE8
"""

#ROOT FINDING USING NEWTON'S METHODS CODE
#There are three parts to this project

#PART A: Set T OL = 10−12 and find the real root of the “Newton’s cubic” x3 − 2x − 5 = 0 (the only equation Newton ever bothered to solve with his method, in 1671 !)

# PART B: In a building, two intersecting halls with widths w1 = 9 feet and w2 = 7 feet meet at an angle α = 125◦, as shown below. Assuming a two-dimensional situation (i.e., ignoring the thickness
#PART B CONT: -of the board), what is the longest board that can negotiate the turn? [Hints: Express length of the board l = l1 + l2 in terms of the angle γ, then find the maximum of the function l(γ) by
#PART B CONT: -solving the nonlinear equation l′(γ) = 0. ].

# PART C: Commissioner Gordon has been found dead in his office. At 8:00pm, the county coroner determined the core temperature of the corpse to be 90◦F. One hour later, the core temper-
#PART C CONT: -ature had dropped to 85◦F. Maintenance reported that the building’s air conditioning unit broke down at 4:00pm. The temperature in the commissioner’s office was 68◦F at that time.
#PART C CONT: -The computerized climate control system recorded that the office temperature rose at a rate of 1◦F per hour after the air conditioning stopped working. Captain Furillo believes that 3
#PART C CONT: -the infamous Doc B killed the commissioner. Doc B, however, claims that he has an alibi. Lois Lane was interviewing him at the Daily Planet Building, just across the street from the
#PART C CONT: -commissioner’s office. The receptionist at the Daily Planet Building checked Doc B into the building at 6:35pm, and the interview tapes confirm that Doc B was occupied from 6:40pm
#PART C CONT: -to 7:15pm. Could Doc B have killed the commissioner?

# Re-usable Newton Function

import math

def newton(F, dF, x0, tol=1e-12, max_iter=100):
    print(f"Initial guess x0 = {x0}")
    print(f"Tolerance = {tol}\n")
    print("{:>3} {:>22} {:>22}".format("n", "xn", "F(xn)"))

# Function starts with x0 initial guess
    x = x0

# Loop through iterations
    for n in range(max_iter):
        fx = F(x)
        print(f"{n:>3} {x:>22.15f} {fx:>22.15e}")

        # First convergence test: residual
        if abs(fx) < tol:
            print("\nIt converged!!")
            print(f"Iterations = {n}")
            print(f"Root = {x:.15f}")
            print(f"Residual = {abs(fx):.15e}")
            return x

        # Derivative of current x
        dfx = dF(x)

        # Check for division by zero
        if dfx == 0:
            print("\nDerivative is 0. Stopped.")
            return None

        # Newton update
        x_next = x - fx / dfx

        # Relative change
        if x != 0:
            relative_change = abs(1 - x_next / x)
        else:
            relative_change = abs(x_next - x)

        # Second convergence test
        if relative_change < tol and abs(F(x_next)) < tol:
            x = x_next
            print(f"{n+1:>3} {x:>22.15f} {F(x):>22.15e}")
            print("\nIt converged!!")
            print(f"Iterations = {n+1}")
            print(f"Root = {x:.15f}")
            print(f"Residual = {abs(F(x)):.15e}")
            return x

        # If convergence hasn't happened, update x
        x = x_next

    # Only gets here if loop finishes without convergence
    print("\nConvergence did not occur.")
    return x

# Helper function to store Newton iterates for plotting
def newton_history(F, dF, x0, tol=1e-12, max_iter=100):

  #Initialize current guess
    x = x0

    #List to store all approximations (starting with initial guess)
    history = [x]

#Peform iterations up to max_iter times
    for n in range(max_iter):

      #Function at the current approx.
        fx = F(x)

#First Convergence check (if F(x) is very small, close to root)
        if abs(fx) < tol:

          #Stop and return all values
            return history

#Evaluate derivative at current approximation
        dfx = dF(x)

#Safety for no division by zero
        if dfx == 0:
            return history #Stops here to avoid breaking the code

#Newton's update using Newtons formula
        x_next = x - fx / dfx
        #Store new approx. for plotting
        history.append(x_next)

#Convergence #2 Check (Relative Change)-- Tells us if the convergence is "stabilizing"
        if x != 0:
            relative_change = abs(1 - x_next / x)
        else:
          #if x=0 avoids division by zero
            relative_change = abs(x_next - x)

#Comdined Convergence condition (small relative change and small residual)
        if relative_change < tol and abs(F(x_next)) < tol:
            return history #Converged (return all stored values)

#Update current approx. for next iteration
        x = x_next

#If max iterations reached without converg. return history anyway (helpful for debugging / diagnostics)
    return history

#Part (a) Test:
def F_a(x):
  return x**3 - 2*x - 5
def dF_a(x):
  return 3*x**2 - 2
root_a = newton(F_a, dF_a, x0=100, tol=1e-12)

# Part (b): Root Finding for L' (gamma) = 0 (Hallway Problem)
import math

#Hallway Lenghts

w1 = 9
w2 = 7

# Hallyway intersection angle (deg)
alpha_deg = 125

#Python trig uses radians not deg so convert (180-alpha for correction)
alpha = (180-alpha_deg)*math.pi/180


#Board length as a function of gamma
def L(gamma):
  return w1 / math.sin(gamma) +w2 / math.sin(alpha-gamma)

#First derivative of the board length: L'(gamma)
def F_b(gamma):
  term1 = -w1 *math.cos(gamma) / (math.sin(gamma)**2)
  term2 = w2 * math.cos(alpha-gamma) / (math.sin(alpha-gamma)**2)
  return term1 +term2

#Second derivative of thr board legnth: L''(gamma)
def dF_b(gamma):
  term1 = w1 * (1/math.sin(gamma)+2 *(math.cos(gamma)**2)/(math.sin(gamma)**3))
  term2 = w2 * (1/ math.sin(alpha-gamma)+2*(math.cos(alpha-gamma)**2)/(math.sin(alpha-gamma)**3))
  return term1 + term2

#Chose an initial guess with stipulation below
gamma0 = 0.5
#Fail-safe
if not (0 < gamma0 < alpha):
    print("\n" + "="*75)
    print("ERROR: Invalid initial guess for gamma.")
    print(f"(that is, between 0 and {alpha:.4f} radians, not including the endpoints).")
    print("Please choose a new initial guess within this interval.")
    print("="*75 + "\n")
else:
#Gamma has to be between 0 and 55 because 180-125= 55, so gamma cannot be greater than that to properly converge
  gamma_root = newton(F_b, dF_b, x0=gamma0, tol=1e-12, max_iter=100)



#Convert gamma back to degrees and calculate the longest board length in ft
gamma_deg = gamma_root * 180 / math.pi
board_length = L(gamma_root)


# Convergence plot for Newton's method part (b)
history_b = newton_history(F_b, dF_b, gamma0, tol=1e-12, max_iter=100)
iterations = list(range(len(history_b)))
history_b_deg = [g * 180 / math.pi for g in history_b]


#Print the Final Answers/Results
print("\n"+ "="*60)
print("Final Results for Part (b)")
print("="*60)
print(f"Critical angle gamma (radians)={gamma_root:.15f}")
print(f"Critical angle gamma (degrees)= {gamma_deg:.15f}")
print(f"Longest board length (feet)= {board_length:.15f}")
print("="*60)

# Visuals for part b:

#Import needed packages:

import numpy as np
import matplotlib.pyplot as plt

# Plot of L(gamma) using degrees on the x-axis

gamma_vals = np.linspace(0.2, alpha - 0.2, 400)
gamma_deg_vals = gamma_vals * 180 / np.pi
L_vals = [L(g) for g in gamma_vals]

plt.figure(figsize=(8, 5))
plt.plot(gamma_deg_vals, L_vals, label='L(gamma)')
plt.plot(gamma_deg, L(gamma_root), 'ro', label='Maximum point')

plt.xlabel('gamma (degrees)')
plt.ylabel('Board length L(gamma) [ft]')
plt.title('Part (b): Board Length as a Function of gamma')
plt.legend()
plt.grid(True)
plt.show()


# Plot of L'(gamma) using degrees on the x-axis

gamma_vals = np.linspace(0.2, alpha - 0.2, 400)
gamma_deg_vals = gamma_vals * 180 / np.pi
Fb_vals = [F_b(g) for g in gamma_vals]

plt.figure(figsize=(8, 5))
plt.plot(gamma_deg_vals, Fb_vals, label="F_b(gamma) = L'(gamma)")
plt.axhline(0, color='black', linestyle='--', linewidth=1)
plt.plot(gamma_deg, F_b(gamma_root), 'ro', label="Root of L'(gamma)")

plt.xlabel('gamma (degrees)')
plt.ylabel("L'(gamma)")
plt.title("Part (b): Root of L'(gamma) Found by Newton's Method")
plt.legend()
plt.grid(True)
plt.show()

#Plot the divergence:
plt.figure(figsize=(8, 5))
plt.plot(iterations, history_b_deg, marker='o', label='gamma_n')

plt.xlabel('Iteration n')
plt.ylabel('Approximation gamma_n (degrees)')
plt.title("Part (b): Convergence of Newton's Method")
plt.legend()
plt.grid(True)
plt.show()

# part (c) Murder Mystery

"""
Making function at 8:00pm

Let t = 0 corresponds to 8:00 pm

At 4:00pm -> 68 F, and rises by 1 F per hr
Means at 8:00 pm it is 72 F
Therefore office temperature becomes 72 + t

Differential Equation:
dT/dt = -k(T - 72 - t), T(0) = 90, T(1) = 85

Solving Diff Eq:
T(t) = 72 + t + C*exp(-k*t) - 1/k

With initial condition T(0) = 90:
90 = 72 + C - 1/k
C = 18 + 1/k

Means:
T(t) = 72 + t + (18 + 1/k)*exp(-k*t) - 1/k

Need to use T(1) = 85 to find k, must use the Newton's method function
"""

# Function to find k
def F_c_k(k):
  return (18*k + 1) * math.exp(-k) - 12*k - 1

# Derivative of F_c_k
def dF_c_k(k):
  return(17 - 18*k) * math.exp(-k) -12

# Initial k assumption
k0 = 0.3

# Solving for k with newton function from (a)
k_root = newton(F_c_k, dF_c_k, x0=k0, tol = 1e-12, max_iter = 100)

# Can make temperture function now that k is found
def T_c(t):
  return 72 + t + (18 + 1/k_root) * math.exp(-k_root * t) - 1/k_root

# Finding time of death where T(t) = 98.6
# New function for time: F_c_t(t) = T(t) - 98.6 = 0
def F_c_t(t):
  return T_c(t) - 98.6

# Derivative of F_c_t(t)
def dF_c_t(t):
  return 1 - (18*k_root + 1) * math.exp(-k_root * t)

# Initial t assumption (must be <0 since death before 8:00 pm)
t0 = -1.0

# Solving for time of death with newton function
t_death = newton(F_c_t, dF_c_t, x0=t0, tol=1e-12, max_iter=100)

# Need to put time into normal clock time
death_hour_raw = 20 + t_death # 20 is 8:00pm for 24 hour time
death_hour = int(death_hour_raw)
death_minute_raw = (death_hour_raw - death_hour) * 60
death_minute = int(death_minute_raw)
death_second = int(round((death_minute_raw - death_minute) * 60))

# Need to fix problems from rounding
if death_second == 60:
  death_second = 0
  death_minute += 1

if death_minute == 60:
  death_minute = 0
  death_hour += 1

# Putting into 12 hour (am - pm) time
if death_hour > 12:
  display_hour = death_hour - 12
  am_pm = "pm"

else:
  display_hour = death_hour
  am_pm = "am"

# Displaying final answers
print("\n" + "="*60)
print("Final Results for Part (c)")
print("="*60)
print(f"Cooling constant k = {k_root:.15f}")
print(f"Time of death relative to 8:00 pm = {t_death:.15f} hours")
print(f"Estimated time of death = {display_hour:02d}:{death_minute:02d}:{death_second:02d} {am_pm}")

# Need to compare results to determine if Doc B's alibi is valid
print("\nDoc B checked in at 6:35 pm and is confered to be busy from 6:40 pm to 7:15 pm.")
if death_hour_raw >= 18 + 40/60 and death_hour_raw <= 19 + 15/60:
  print("Conclusion: \nThe estimated time of death happens during Doc B's alibi.")
  print("Doc B did not kill Commissioner Gordon.")
else:
  print("Conclusion: \nThe estimated time of death does not happen for the whole duration of Doc B's alibi.")
  print("Doc B is still a reasonable suspect.")
print("="*60)

# Convergence for the time of death calculation
history_c = newton_history(F_c_t, dF_c_t, t0, tol=1e-12, max_iter=100)
iterations_c = list(range(len(history_c)))

# Plotting convergence
plt.figure(figsize=(8,6))
plt.plot(iterations_c, history_c, marker='o', label='t_n')
plt.xlabel('Iteration n')
plt.ylabel('Approximation t_n (hours from 8:00 pm)')
plt.title("Part (c): Convergence of Newton's Method for Time of Death")
plt.legend()
plt.grid(True)
plt.show()